### ISSUE TITLE
AssertionError: Paged attention required Flash Attention 2.5.7 or later [BUG]

### ISSUE THREAD

**Issue by ialhabbal** [theroyallab/tabbyAPI#120]
I updated TabbyAPI and now have ExllamaV2 version: 0.1.1. I added a model name in the config.yml and when I try to run the main.py in a virtual environment like I did in the previous version I get the below error:

Loading model modules ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 67/67 0:00:00
Traceback (most recent call last):
  File "L:\tabbyAPI\main.py", line 121, in <module>
    asyncio.run(entrypoint())
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "L:\tabbyAPI\main.py", line 109, in entrypoint
    await model.load_model(model_path.resolve(), **model_config)
  File "L:\tabbyAPI\common\model.py", line 78, in load_model
    async for _ in load_model_gen(model_path, **kwargs):
  File "L:\tabbyAPI\common\model.py", line 58, in load_model_gen
    async for module, modules in load_status:
  File "L:\tabbyAPI\backends\exllamav2\model.py", line 462, in load_gen
    self.generator = ExLlamaV2DynamicGeneratorAsync(
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\exllamav2\generator\dynamic_async.py", line 16, in __init__
    self.generator = ExLlamaV2DynamicGenerator(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\exllamav2\generator\dynamic.py", line 321, in __init__
    assert_paged_attn()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\exllamav2\attn.py", line 60, in assert_paged_attn
    assert has_flash_attn_with_paged, \
AssertionError: Paged attention required Flash Attention 2.5.7 or later

I have tried to install Flash Attention but I hit a dead end with the help of ChatGPT, Gemini, and CoPilot.

**Comment by DocShotgun** [comment]
Per discussion in the royallab discord, flash attention failed to install due to using CUDA 11.8 on Windows, which is a configuration that flash attention 2 does not support.

Tabby does need more robust checks for cases in which a user's hardware supports flash attention 2, but they are not using flash attention 2 (either intentionally or unintentionally) for whatever reason.

**Comment by zewt** [comment]
Would it be better if exllamav2 treated "paged" as optional and falls back (with a warning), so each client application doesn't have to check for this separately (and stay in sync with the version it needs to check for)?

**Comment by DocShotgun** [comment]
> Would it be better if exllamav2 treated "paged" as optional and falls back (with a warning), so each client application doesn't have to check for this separately (and stay in sync with the version it needs to check for)?

This should be addressed in the PR.

Currently, Tabby just isn't checking for all possible ways that users could have a configuration that doesn't work with paged mode. It's only checking for unsupported GPU arch.
