### ISSUE TITLE
[REQUEST] Support for Gemma2ForCasualLM Models

### ISSUE THREAD

**Issue by official-elinas** [theroyallab/tabbyAPI#142]
**Is your feature request related to a problem? Please describe.**
Please add support for Gemma2ForCasualLM models

**Describe the solution you'd like**
Implementation so it doesn't fallback on Llama (stack below)

**Describe alternatives you've considered**
LlamaCPP

**Why should this feature be added?**
It's a new model that is reported to be highly performant and would be great to load in EXL2 as well as full precision (bf16/fp16)

**Stack Trace**
```
!! Warning, unknown architecture: Gemma2ForCausalLM
 !! Loading as LlamaForCausalLM
Traceback (most recent call last):
  File "/media/npetro/nvme_1/tabbyAPI/start.py", line 162, in <module>
    asyncio.run(entrypoint(convert_args_to_dict(args, parser)))
  File "/home/linuxbrew/.linuxbrew/opt/python@3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/media/npetro/nvme_1/tabbyAPI/main.py", line 109, in entrypoint
    await model.load_model(model_path.resolve(), **model_config)
  File "/media/npetro/nvme_1/tabbyAPI/common/model.py", line 79, in load_model
    async for _ in load_model_gen(model_path, **kwargs):
  File "/media/npetro/nvme_1/tabbyAPI/common/model.py", line 49, in load_model_gen
    container = ExllamaV2Container(model_path.resolve(), False, **kwargs)
  File "/media/npetro/nvme_1/tabbyAPI/backends/exllamav2/model.py", line 174, in __init__
    self.config.prepare()
  File "/media/npetro/nvme_1/tabbyAPI/venv/lib/python3.10/site-packages/exllamav2/config.py", line 333, in prepare
    raise ValueError(f" ## Could not find {prefix}.* in model")
ValueError:  ## Could not find lm_head.* in model
```

Thanks @turboderp and @bdashore3!

**Comment by bdashore3** [comment]
Hey there, this issue would better be placed in [ExllamaV2's github](https://github.com/turboderp/exllamav2/issues). Once it's added there, tabby should work with the correct wheel.
