### ISSUE TITLE
[BUG] Failed to import chat template fron `config.json`

### ISSUE THREAD

**Issue by Orion-zhen** [theroyallab/tabbyAPI#167]
### OS

Linux

### GPU Library

CUDA 12.x

### Python version

3.12

### Describe the bug

tabbyAPI simply failed to load chat template from the `config.json`

### Reproduction steps

update to the latest repo, and run `python start.py`

### Expected behavior

model should load successfully, with chat template loaded from `config.json`

### Logs

```shell
INFO:     Attempting to load a prompt template if present.
ERROR:    Traceback (most recent call last):
ERROR:      File "/home/orion/ai/tabbyAPI/backends/exllamav2/model.py", line 384, in find_prompt_template
ERROR:        prompt_template = template_func()
ERROR:                          ^^^^^^^^^^^^^^^
ERROR:      File "/home/orion/ai/tabbyAPI/backends/exllamav2/model.py", line 363, in <lambda>
ERROR:        lambda: PromptTemplate.from_model_json(
ERROR:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR:      File "/home/orion/ai/tabbyAPI/common/templating.py", line 155, in from_model_json
ERROR:        return PromptTemplate(
ERROR:               ^^^^^^^^^^^^^^^
ERROR:      File "/home/orion/ai/tabbyAPI/common/templating.py", line 96, in __init__
ERROR:        self.metadata = self.extract_metadata()
ERROR:                        ^^^^^^^^^^^^^^^^^^^^^^^
ERROR:      File "/home/orion/ai/tabbyAPI/common/templating.py", line 44, in extract_metadata
ERROR:        template_module = self.template.make_module()
ERROR:                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR:      File "/home/orion/ai/tabbyAPI/.venv/lib/python3.12/site-packages/jinja2/environment.py", line 1408, in make_module
ERROR:        return TemplateModule(self, ctx)
ERROR:               ^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR:      File "/home/orion/ai/tabbyAPI/.venv/lib/python3.12/site-packages/jinja2/environment.py", line 1540, in __init__
ERROR:        body_stream = list(template.root_render_func(context))
ERROR:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR:      File "<template>", line 71, in root
ERROR:      File "/home/orion/ai/tabbyAPI/.venv/lib/python3.12/site-packages/jinja2/sandbox.py", line 304, in getitem
ERROR:        return obj[argument]
ERROR:               ~~~^^^^^^^^^^
ERROR:      File "/home/orion/ai/tabbyAPI/.venv/lib/python3.12/site-packages/jinja2/runtime.py", line 857, in _fail_with_undefined_error
ERROR:        raise self._undefined_exception(self._undefined_message)
ERROR:    jinja2.exceptions.UndefinedError: 'messages' is undefined
WARNING:  An unexpected error happened when trying to load the template. Trying other methods.
WARNING:  TemplateLoadError: Could not find template from model name.
WARNING:  Chat completions are disabled because a prompt template wasn't provided or auto-detected.
```

### Additional context

this bug is detected after my latest `git pull`, it could have something to do with your latest commit.

### Acknowledgements

- [X] I have looked for similar issues before submitting this one.
- [X] I have read the disclaimer, and this issue is related to a code bug. If I have a question, I will use the Discord server.
- [X] I understand that the developers have lives and my issue will be answered when possible.
- [X] I understand the developers of this program are human, and I will ask my questions politely.

**Comment by Orion-zhen** [comment]
I reset my head to right before [pr154](https://github.com/theroyallab/tabbyAPI/pull/154) and there is no bug. As my debug experience indecates, line 44 in `common/templating.py`: `template_module = self.template.make_module()` is not successfully parsing chat template.

**Comment by bdashore3** [comment]
See b4752c1e62c8daa27246f3e0583eeb3e7c4ad27f

**Comment by Orion-zhen** [comment]
> See [b4752c1](https://github.com/theroyallab/tabbyAPI/commit/b4752c1e62c8daa27246f3e0583eeb3e7c4ad27f)

Issue solved, thanks!
