### ISSUE TITLE
[BUG] 'TabbyConfig' object has no attribute 'from_file'. Did you mean: '_from_file'?

### ISSUE THREAD

**Issue by atisharma** [theroyallab/tabbyAPI#196]
### OS

Linux

### GPU Library

CUDA 12.x

### Python version

3.11

### Describe the bug

There's a typo in common/tabby_config.py which breaks config file loading.

### Reproduction steps

$ python main.py --config my_config.yml

### Expected behavior

Should use the config file.

### Logs

```
INFO:     Config file override detected in args.
Traceback (most recent call last):
  File "/tabbyAPI/main.py", line 171, in <module>
    entrypoint()
  File "/tabbyAPI/main.py", line 113, in entrypoint
    config.load(arguments)
  File "/tabbyAPI/common/tabby_config.py", line 25, in load
    self._from_args(unwrap(arguments, {})),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tabbyAPI/common/tabby_config.py", line 64, in _from_args
    config = self.from_file(pathlib.Path(config_override))
             ^^^^^^^^^^^^^^
AttributeError: 'TabbyConfig' object has no attribute 'from_file'. Did you mean: '_from_file'?
```

### Additional context

The error is here.

https://github.com/theroyallab/tabbyAPI/blob/c11461e22f741ff5ecad60e700beda9f5d981368/common/tabby_config.py#L64

### Acknowledgements

- [X] I have looked for similar issues before submitting this one.
- [X] I have read the disclaimer, and this issue is related to a code bug. If I have a question, I will use the Discord server.
- [X] I understand that the developers have lives and my issue will be answered when possible.
- [X] I understand the developers of this program are human, and I will ask my questions politely.

**Comment by atisharma** [comment]
I made a PR  #197
