### ISSUE TITLE
[BUG] v1/template/switch is broken

### ISSUE THREAD

**Issue by SecretiveShell** [theroyallab/tabbyAPI#198]
### OS

Windows

### GPU Library

CUDA 12.x

### Python version

3.12

### Describe the bug

There is an issue with internal data types inside of tabbyAPI

### Reproduction steps

```bash
curl -X 'POST' \
  'http://localhost:5000/v1/template/switch' \
  -H 'accept: application/json' \
  -H 'x-admin-key: API_KEY' \
  -H 'Content-Type: application/json' \
  -d '{
  "name": "alpaca"
}'
```

### Expected behavior

The template should load

### Logs

```python
INFO:     127.0.0.1:50817 - "POST /v1/template/switch HTTP/1.1" 500
ERROR:    Exception in ASGI application
ERROR:    Traceback (most recent call last):
ERROR:      File "C:\Users\username\Documents\tabbyAPI-fork\venv\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 401, in run_asgi
ERROR:        result = await app(  # type: ignore[func-returns-value]
ERROR:                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR:      File "C:\Users\username\Documents\tabbyAPI-fork\venv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
ERROR:        return await self.app(scope, receive, send)
ERROR:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR:      File "C:\Users\username\Documents\tabbyAPI-fork\venv\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
ERROR:        await super().__call__(scope, receive, send)
ERROR:      File "C:\Users\username\Documents\tabbyAPI-fork\venv\Lib\site-packages\starlette\applications.py", line 113, in __call__
ERROR:        await self.middleware_stack(scope, receive, send)
ERROR:      File "C:\Users\username\Documents\tabbyAPI-fork\venv\Lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
ERROR:        raise exc
ERROR:      File "C:\Users\username\Documents\tabbyAPI-fork\venv\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
ERROR:        await self.app(scope, receive, _send)
ERROR:      File "C:\Users\username\Documents\tabbyAPI-fork\venv\Lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
ERROR:        await self.app(scope, receive, send)
ERROR:      File "C:\Users\username\Documents\tabbyAPI-fork\venv\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
ERROR:        await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
ERROR:      File "C:\Users\username\Documents\tabbyAPI-fork\venv\Lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
ERROR:        raise exc
ERROR:      File "C:\Users\username\Documents\tabbyAPI-fork\venv\Lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
ERROR:        await app(scope, receive, sender)
ERROR:      File "C:\Users\username\Documents\tabbyAPI-fork\venv\Lib\site-packages\starlette\routing.py", line 715, in __call__
ERROR:        await self.middleware_stack(scope, receive, send)
ERROR:      File "C:\Users\username\Documents\tabbyAPI-fork\venv\Lib\site-packages\starlette\routing.py", line 735, in app
ERROR:        await route.handle(scope, receive, send)
ERROR:      File "C:\Users\username\Documents\tabbyAPI-fork\venv\Lib\site-packages\starlette\routing.py", line 288, in handle
ERROR:        await self.app(scope, receive, send)
ERROR:      File "C:\Users\username\Documents\tabbyAPI-fork\venv\Lib\site-packages\starlette\routing.py", line 76, in app
ERROR:        await wrap_app_handling_exceptions(app, request)(scope, receive, send)
ERROR:      File "C:\Users\username\Documents\tabbyAPI-fork\venv\Lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
ERROR:        raise exc
ERROR:      File "C:\Users\username\Documents\tabbyAPI-fork\venv\Lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
ERROR:        await app(scope, receive, sender)
ERROR:      File "C:\Users\username\Documents\tabbyAPI-fork\venv\Lib\site-packages\starlette\routing.py", line 73, in app
ERROR:        response = await f(request)
ERROR:                   ^^^^^^^^^^^^^^^^
ERROR:      File "C:\Users\username\Documents\tabbyAPI-fork\venv\Lib\site-packages\fastapi\routing.py", line 301, in app
ERROR:        raw_response = await run_endpoint_function(
ERROR:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR:      File "C:\Users\username\Documents\tabbyAPI-fork\venv\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
ERROR:        return await dependant.call(**values)
ERROR:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR:      File "C:\Users\username\Documents\tabbyAPI-fork\endpoints\core\router.py", line 448, in switch_template
ERROR:        model.container.prompt_template = PromptTemplate.from_file(data.name)
ERROR:                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR:      File "C:\Users\username\Documents\tabbyAPI-fork\common\templating.py", line 117, in from_file
ERROR:        if template_path.suffix.endswith(".jinja"):
ERROR:           ^^^^^^^^^^^^^^^^^^^^
ERROR:    AttributeError: 'str' object has no attribute 'suffix'
```

### Additional context

if on windows run the curl command in git bash

### Acknowledgements

- [X] I have looked for similar issues before submitting this one.
- [X] I have read the disclaimer, and this issue is related to a code bug. If I have a question, I will use the Discord server.
- [X] I understand that the developers have lives and my issue will be answered when possible.
- [X] I understand the developers of this program are human, and I will ask my questions politely.

**Comment by bdashore3** [comment]
Fixed in 54bfb770af25ec65dc8160e3ce17e4cba0d7e92e
