### ISSUE TITLE
[BUG] TabbyAPI uses 100% of a CPU core after a request failed due to excessively long prompt

### ISSUE THREAD

**Issue by NeoChen1024** [theroyallab/tabbyAPI#203]
### OS

Linux

### GPU Library

CUDA 12.x

### Python version

3.12

### Describe the bug

TabbyAPI uses 100% of a CPU core after a request failed due to excessively long prompt.
For example, TabbyAPI was started with max-seq-len=8192, and I feed it with more than 8192 tokens of prompt. After the request failed, I sent it another normal request that didn't fail. and TabbyAPI starts using 100% of a single CPU core after it's already idle.
![screenshot](https://github.com/user-attachments/assets/3e452ffe-8338-4476-b178-ea95ae9e77ac)

When I looked at strace, it seems to be executing a infinite loop of epoll.
![strace](https://github.com/user-attachments/assets/982aa998-82f1-48bb-ab81-9480e51a217b)

Settings: it happens regardless of whether uvloop and CUDA malloc are enabled/disabled

Version: git latest at 2024-09-17 (2a41910931072cdaf00f920b50e3f487cc92f05c)
OS: Arch Linux w/ nvidia-open-dkms 560.35.03-6
GPU: 3090Ti
Loaded model: LoneStriker/dolphin-2.7-mixtral-8x7b-3.75bpw-h6-exl2 or LoneStriker_dolphin-2.7-mixtral-8x7b-3.0bpw-h6-exl2
max-seq-len: 32768 (about 200MiBs from VRAM OOM at 3.75bpw, far from it at 3.0bpw)

### Reproduction steps

1. Send a request with more prompt tokens than available cache size
2. Send another normal request
3. Its CPU usage stays high even in idle

### Expected behavior

CPU usage return to 0% when it's idle.

### Logs

```
Activating venv
pip 24.2 from /home/neo_chen/vcs/AI/tabbyAPI/venv/lib/python3.12/site-packages/pip (python 3.12)
Loaded your saved preferences from `start_options.json`
No ROCm runtime is found, using ROCM_HOME='/opt/rocm'
Starting TabbyAPI...
INFO:     ExllamaV2 version: 0.2.2
INFO:     Your API key is: XX
INFO:     Your admin key is: XX
INFO:
INFO:     If these keys get compromised, make sure to delete api_tokens.yml and restart the server.
Have fun!
INFO:     Generation logging is disabled
INFO:     Disabling GPU split because one GPU is in use.
WARNING:  The given cache_size (32768) is less than 2 * max_seq_len and may be too small for requests
using CFG.
WARNING:  Ignore this warning if you do not plan on using CFG.
INFO:     Attempting to load a prompt template if present.
INFO:     Using template "from_tokenizer_config" for chat completions.
INFO:     Loading model: /home/neo_chen/models/LoneStriker_dolphin-2.7-mixtral-8x7b-3.75bpw-h6-exl2
INFO:     Loading with a manual GPU split (or a one GPU setup)
Loading model modules ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 67/67 0:00:00
INFO:     Model successfully loaded.
INFO:     Developer documentation: http://0.0.0.0:5000/redoc
INFO:     Starting OAI API
INFO:     Completions: http://0.0.0.0:5000/v1/completions
INFO:     Chat completions: http://0.0.0.0:5000/v1/chat/completions
INFO:     Started server process [835938]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:5000 (Press CTRL+C to quit)
INFO:     127.0.0.1:40740 - "POST /v1/token/encode HTTP/1.1" 200
INFO:     127.0.0.1:40754 - "POST /v1/completions HTTP/1.1" 200
INFO:     Received streaming completion request a2ee02853e704c72bc88ba045956298b
INFO:     Finished streaming completion request a2ee02853e704c72bc88ba045956298b
INFO:     Metrics (ID: a2ee02853e704c72bc88ba045956298b): 270 tokens generated in 20.48 seconds (Queue:
0.0 s, Process: 0 cached tokens and 30385 new tokens at 2312.84 T/s, Generate: 36.78 T/s, Context:
30385 tokens)
INFO:     127.0.0.1:45254 - "POST /v1/token/encode HTTP/1.1" 200
INFO:     127.0.0.1:56758 - "POST /v1/token/encode HTTP/1.1" 200
INFO:     127.0.0.1:56774 - "POST /v1/completions HTTP/1.1" 200
INFO:     Received streaming completion request 9510495de3894fa68b588ca55ef925a6
WARNING:  Context length 33971 is greater than max_seq_len 32768. Generation is truncated and metrics
may not be accurate.
ERROR:    Traceback (most recent call last):
ERROR:      File "/home/neo_chen/vcs/AI/tabbyAPI/endpoints/OAI/utils/completion.py", line 202, in
stream_generate_completion
ERROR:        raise generation
ERROR:      File "/home/neo_chen/vcs/AI/tabbyAPI/endpoints/OAI/utils/completion.py", line 101, in
_stream_collector
ERROR:        async for generation in new_generation:
ERROR:      File "/home/neo_chen/vcs/AI/tabbyAPI/backends/exllamav2/model.py", line 1256, in
generate_gen
ERROR:        job = ExLlamaV2DynamicJobAsync(
ERROR:              ^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR:      File
"/home/neo_chen/vcs/AI/tabbyAPI/venv/lib/python3.12/site-packages/exllamav2/generator/dynamic_async.py"
, line 84, in __init__
ERROR:        self.generator.enqueue(self)
ERROR:      File
"/home/neo_chen/vcs/AI/tabbyAPI/venv/lib/python3.12/site-packages/exllamav2/generator/dynamic_async.py"
, line 47, in enqueue
ERROR:        self.generator.enqueue(job.job)
ERROR:      File
"/home/neo_chen/vcs/AI/tabbyAPI/venv/lib/python3.12/site-packages/exllamav2/generator/dynamic.py", line
810, in enqueue
ERROR:        job.prepare_for_queue(self, self.job_serial)
ERROR:      File
"/home/neo_chen/vcs/AI/tabbyAPI/venv/lib/python3.12/site-packages/exllamav2/generator/dynamic.py", line
2151, in prepare_for_queue
ERROR:        assert total_pages \<= self.generator.max_pages, \
ERROR:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR:    AssertionError: Job requires 135 pages (only 128 available) and cannot be enqueued. Total
cache allocated is 128 * 256 = 32768 tokens
ERROR:    Sent to request: Completion 9510495de3894fa68b588ca55ef925a6 aborted. Please check the server
console.
INFO:     127.0.0.1:46314 - "POST /v1/token/encode HTTP/1.1" 200
INFO:     127.0.0.1:46316 - "POST /v1/completions HTTP/1.1" 200
INFO:     Received streaming completion request 55d91401d1e04045af6982ee2feac293
INFO:     Finished streaming completion request 55d91401d1e04045af6982ee2feac293
INFO:     Metrics (ID: 55d91401d1e04045af6982ee2feac293): 500 tokens generated in 24.17 seconds (Queue:
0.0 s, Process: 1280 cached tokens and 26558 new tokens at 2346.84 T/s, Generate: 38.91 T/s, Context:
27838 tokens)
INFO:     127.0.0.1:44856 - "POST /v1/token/encode HTTP/1.1" 200
^CINFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [835938]
WARNING:  Shutdown signal called. Exiting gracefully.
INFO:     Model unloaded.
./start.sh  653.53s user 27.41s system 91% cpu 12:20.98 total
```

### Acknowledgements

- [X] I have looked for similar issues before submitting this one.
- [X] I have read the disclaimer, and this issue is related to a code bug. If I have a question, I will use the Discord server.
- [X] I understand that the developers have lives and my issue will be answered when possible.
- [X] I understand the developers of this program are human, and I will ask my questions politely.

**Comment by bdashore3** [comment]
Should hopefully be fixed with 75af974c8802e3e471943563970a9690365751a5
