### ISSUE TITLE
[BUG] EXL2 v0.2.5+ is broken with yarn RoPE.

### ISSUE THREAD

**Issue by Originalimoc** [theroyallab/tabbyAPI#261]
### OS

Linux

### GPU Library

CUDA 12.x

### Python version

3.11

### Describe the bug

See log.

### Reproduction steps

Load a model with yarn, Like Qwen2.5-14B-Ins.

### Expected behavior

It loads.

### Logs

```
ERROR:    Exception in ASGI application
ERROR:    Traceback (most recent call last):
ERROR:      File
"/home/imoc/miniconda3/envs/tabbyAPI/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 401,
in run_asgi
ERROR:        result = await app(  # type: ignore[func-returns-value]
ERROR:                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR:      File "/home/imoc/miniconda3/envs/tabbyAPI/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py",
line 60, in __call__
ERROR:        return await self.app(scope, receive, send)
ERROR:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR:      File "/home/imoc/miniconda3/envs/tabbyAPI/lib/python3.11/site-packages/fastapi/applications.py", line 1054,
in __call__
ERROR:        await super().__call__(scope, receive, send)
ERROR:      File "/home/imoc/miniconda3/envs/tabbyAPI/lib/python3.11/site-packages/starlette/applications.py", line 113,
in __call__
ERROR:        await self.middleware_stack(scope, receive, send)
ERROR:      File "/home/imoc/miniconda3/envs/tabbyAPI/lib/python3.11/site-packages/starlette/middleware/errors.py", line
187, in __call__
ERROR:        raise exc
ERROR:      File "/home/imoc/miniconda3/envs/tabbyAPI/lib/python3.11/site-packages/starlette/middleware/errors.py", line
165, in __call__
ERROR:        await self.app(scope, receive, _send)
ERROR:      File "/home/imoc/miniconda3/envs/tabbyAPI/lib/python3.11/site-packages/starlette/middleware/cors.py", line
85, in __call__
ERROR:        await self.app(scope, receive, send)
ERROR:      File "/home/imoc/miniconda3/envs/tabbyAPI/lib/python3.11/site-packages/starlette/middleware/exceptions.py",
line 62, in __call__
ERROR:        await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
ERROR:      File "/home/imoc/miniconda3/envs/tabbyAPI/lib/python3.11/site-packages/starlette/_exception_handler.py",
line 53, in wrapped_app
ERROR:        raise exc
ERROR:      File "/home/imoc/miniconda3/envs/tabbyAPI/lib/python3.11/site-packages/starlette/_exception_handler.py",
line 42, in wrapped_app
ERROR:        await app(scope, receive, sender)
ERROR:      File "/home/imoc/miniconda3/envs/tabbyAPI/lib/python3.11/site-packages/starlette/routing.py", line 715, in
__call__
ERROR:        await self.middleware_stack(scope, receive, send)
ERROR:      File "/home/imoc/miniconda3/envs/tabbyAPI/lib/python3.11/site-packages/starlette/routing.py", line 735, in
app
ERROR:        await route.handle(scope, receive, send)
ERROR:      File "/home/imoc/miniconda3/envs/tabbyAPI/lib/python3.11/site-packages/starlette/routing.py", line 288, in
handle
ERROR:        await self.app(scope, receive, send)
ERROR:      File "/home/imoc/miniconda3/envs/tabbyAPI/lib/python3.11/site-packages/starlette/routing.py", line 76, in
app
ERROR:        await wrap_app_handling_exceptions(app, request)(scope, receive, send)
ERROR:      File "/home/imoc/miniconda3/envs/tabbyAPI/lib/python3.11/site-packages/starlette/_exception_handler.py",
line 53, in wrapped_app
ERROR:        raise exc
ERROR:      File "/home/imoc/miniconda3/envs/tabbyAPI/lib/python3.11/site-packages/starlette/_exception_handler.py",
line 42, in wrapped_app
ERROR:        await app(scope, receive, sender)
ERROR:      File "/home/imoc/miniconda3/envs/tabbyAPI/lib/python3.11/site-packages/starlette/routing.py", line 73, in
app
ERROR:        response = await f(request)
ERROR:                   ^^^^^^^^^^^^^^^^
ERROR:      File "/home/imoc/miniconda3/envs/tabbyAPI/lib/python3.11/site-packages/fastapi/routing.py", line 301, in app
ERROR:        raw_response = await run_endpoint_function(
ERROR:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR:      File "/home/imoc/miniconda3/envs/tabbyAPI/lib/python3.11/site-packages/fastapi/routing.py", line 212, in
run_endpoint_function
ERROR:        return await dependant.call(**values)
ERROR:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR:      File "/mnt/c/Users/imoc/Desktop/gpt4all/exe/tabbyAPI/git/endpoints/OAI/router.py", line 112, in
chat_completion_request
ERROR:        await load_inline_model(data.model, request)
ERROR:      File "/mnt/c/Users/imoc/Desktop/gpt4all/exe/tabbyAPI/git/endpoints/OAI/utils/completion.py", line 172, in
load_inline_model
ERROR:        await model.load_model(
ERROR:      File "/mnt/c/Users/imoc/Desktop/gpt4all/exe/tabbyAPI/git/common/model.py", line 112, in load_model
ERROR:        async for _ in load_model_gen(model_path, **kwargs):
ERROR:      File "/mnt/c/Users/imoc/Desktop/gpt4all/exe/tabbyAPI/git/common/model.py", line 90, in load_model_gen
ERROR:        async for module, modules in load_status:
ERROR:      File "/mnt/c/Users/imoc/Desktop/gpt4all/exe/tabbyAPI/git/backends/exllamav2/model.py", line 574, in load_gen
ERROR:        async for value in iterate_in_threadpool(model_load_generator):
ERROR:      File "/mnt/c/Users/imoc/Desktop/gpt4all/exe/tabbyAPI/git/common/concurrency.py", line 30, in
iterate_in_threadpool
ERROR:        yield await asyncio.to_thread(gen_next, generator)
ERROR:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR:      File "/home/imoc/miniconda3/envs/tabbyAPI/lib/python3.11/asyncio/threads.py", line 25, in to_thread
ERROR:        return await loop.run_in_executor(None, func_call)
ERROR:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR:      File "/home/imoc/miniconda3/envs/tabbyAPI/lib/python3.11/concurrent/futures/thread.py", line 58, in run
ERROR:        result = self.fn(*self.args, **self.kwargs)
ERROR:                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR:      File "/mnt/c/Users/imoc/Desktop/gpt4all/exe/tabbyAPI/git/common/concurrency.py", line 20, in gen_next
ERROR:        return next(generator)
ERROR:               ^^^^^^^^^^^^^^^
ERROR:      File "/home/imoc/miniconda3/envs/tabbyAPI/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 57,
in generator_context
ERROR:        response = gen.send(request)
ERROR:                   ^^^^^^^^^^^^^^^^^
ERROR:      File "/mnt/c/Users/imoc/Desktop/gpt4all/exe/tabbyAPI/git/backends/exllamav2/model.py", line 683, in
load_model_sync
ERROR:        for value in self.model.load_gen(
ERROR:      File "/home/imoc/miniconda3/envs/tabbyAPI/lib/python3.11/site-packages/exllamav2/model.py", line 333, in
load_gen
ERROR:        module.load()
ERROR:      File "/home/imoc/miniconda3/envs/tabbyAPI/lib/python3.11/site-packages/torch/utils/_contextlib.py", line
116, in decorate_context
ERROR:        return func(*args, **kwargs)
ERROR:               ^^^^^^^^^^^^^^^^^^^^^
ERROR:      File "/home/imoc/miniconda3/envs/tabbyAPI/lib/python3.11/site-packages/exllamav2/attn.py", line 244, in load
ERROR:        self.q_proj.load(device_context = device_context)
ERROR:      File "/home/imoc/miniconda3/envs/tabbyAPI/lib/python3.11/site-packages/torch/utils/_contextlib.py", line
116, in decorate_context
ERROR:        return func(*args, **kwargs)
ERROR:               ^^^^^^^^^^^^^^^^^^^^^
ERROR:      File "/home/imoc/miniconda3/envs/tabbyAPI/lib/python3.11/site-packages/exllamav2/linear.py", line 138, in
load
ERROR:        device_context = self.model.get_device_context(self.device_idx)
ERROR:                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR:      File "/home/imoc/miniconda3/envs/tabbyAPI/lib/python3.11/site-packages/exllamav2/model.py", line 730, in
get_device_context
ERROR:        if not context.ready: context.prepare(scratch)
ERROR:                              ^^^^^^^^^^^^^^^^^^^^^^^^
ERROR:      File "/home/imoc/miniconda3/envs/tabbyAPI/lib/python3.11/site-packages/exllamav2/device.py", line 78, in
prepare
ERROR:        self.prepare_sincos()
ERROR:      File "/home/imoc/miniconda3/envs/tabbyAPI/lib/python3.11/site-packages/exllamav2/device.py", line 136, in
prepare_sincos
ERROR:        inv_freq, scaling_factor = rope.get_rope_params(device, cfg)
ERROR:                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR:      File "/home/imoc/miniconda3/envs/tabbyAPI/lib/python3.11/site-packages/exllamav2/rope.py", line 161, in
get_rope_params
ERROR:        inv_freq, scaling_factor = get_rope_params_yarn(device, cfg)
ERROR:                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR:      File "/home/imoc/miniconda3/envs/tabbyAPI/lib/python3.11/site-packages/exllamav2/rope.py", line 137, in
get_rope_params_yarn
ERROR:        return inv_freq, scaling_factor
ERROR:                         ^^^^^^^^^^^^^^
ERROR:    UnboundLocalError: cannot access local variable 'scaling_factor' where it is not associated with a value
```

### Acknowledgements

- [X] I have looked for similar issues before submitting this one.
- [X] I have read the disclaimer, and this issue is related to a code bug. If I have a question, I will use the Discord server.
- [X] I understand that the developers have lives and my issue will be answered when possible.
- [X] I understand the developers of this program are human, and I will ask my questions politely.

**Comment by DocShotgun** [comment]
Fixed by https://github.com/turboderp/exllamav2/commit/af69ce94589d5f74b4e55206a23d42c25734c7f5

**Comment by bdashore3** [comment]
This is an exl2 bug and isn't directly related to tabbyAPI. Since doc linked a commit that fixes this problem, I'd advise installing exl2 from the dev branch into tabby's venv.

If you have any more problems with exl2, please open an issue in [its repo](https://github.com/turboderp/exllamav2).

**Comment by DocShotgun** [comment]
This error also only occurs if you have yarn enabled in the model's `config.json` however you are loading the model with such a low context size that yarn isn't actually needed, so you could temporarily work around it by removing yarn from the `config.json` unless needing to load with larger context size, if you don't wish to install exllamav2 dev from source.
