### ISSUE TITLE
[BUG] Embedding generation API causes exception when requesting base64 encoding

### ISSUE THREAD

**Issue by aurath** [theroyallab/tabbyAPI#268]
### OS

Windows

### GPU Library

CUDA 12.x

### Python version

3.12

### Describe the bug

When the `encoding_format` json field in an embedding request is set to `base64`, it returns a 500 response. It looks to me like `get_embeddings()` in embeddings.py ends up with a base64 string where it's expecting a list. The .Net OpenAI client turns this field on and it's not easy to disable the behavior.

### Reproduction steps

Make an arbitrary embedding API request with `"encoding_format":"base64"` in the json body.

### Expected behavior

Expect a normal 200 response with embedding content.

### Logs

INFO:     127.0.0.1:56257 - "POST /v1/embeddings HTTP/1.1" 500
ERROR:    Exception in ASGI application
ERROR:    Traceback (most recent call last):
ERROR:      File "C:\Users\XXX\tabbyAPI\venv\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in
run_asgi
ERROR:        result = await app(  # type: ignore[func-returns-value]
ERROR:                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR:      File "C:\Users\XXX\tabbyAPI\venv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in
__call__
ERROR:        return await self.app(scope, receive, send)
ERROR:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR:      File "C:\Users\XXX\tabbyAPI\venv\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
ERROR:        await super().__call__(scope, receive, send)
ERROR:      File "C:\Users\XXX\tabbyAPI\venv\Lib\site-packages\starlette\applications.py", line 113, in __call__
ERROR:        await self.middleware_stack(scope, receive, send)
ERROR:      File "C:\Users\XXX\tabbyAPI\venv\Lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
ERROR:        raise exc
ERROR:      File "C:\Users\XXX\tabbyAPI\venv\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
ERROR:        await self.app(scope, receive, _send)
ERROR:      File "C:\Users\XXX\tabbyAPI\venv\Lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
ERROR:        await self.app(scope, receive, send)
ERROR:      File "C:\Users\XXX\tabbyAPI\venv\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in
__call__
ERROR:        await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
ERROR:      File "C:\Users\XXX\tabbyAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in
wrapped_app
ERROR:        raise exc
ERROR:      File "C:\Users\XXX\tabbyAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in
wrapped_app
ERROR:        await app(scope, receive, sender)
ERROR:      File "C:\Users\XXX\tabbyAPI\venv\Lib\site-packages\starlette\routing.py", line 715, in __call__
ERROR:        await self.middleware_stack(scope, receive, send)
ERROR:      File "C:\Users\XXX\tabbyAPI\venv\Lib\site-packages\starlette\routing.py", line 735, in app
ERROR:        await route.handle(scope, receive, send)
ERROR:      File "C:\Users\XXX\tabbyAPI\venv\Lib\site-packages\starlette\routing.py", line 288, in handle
ERROR:        await self.app(scope, receive, send)
ERROR:      File "C:\Users\XXX\tabbyAPI\venv\Lib\site-packages\starlette\routing.py", line 76, in app
ERROR:        await wrap_app_handling_exceptions(app, request)(scope, receive, send)
ERROR:      File "C:\Users\XXX\tabbyAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in
wrapped_app
ERROR:        raise exc
ERROR:      File "C:\Users\XXX\tabbyAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in
wrapped_app
ERROR:        await app(scope, receive, sender)
ERROR:      File "C:\Users\XXX\tabbyAPI\venv\Lib\site-packages\starlette\routing.py", line 73, in app
ERROR:        response = await f(request)
ERROR:                   ^^^^^^^^^^^^^^^^
ERROR:      File "C:\Users\XXX\tabbyAPI\venv\Lib\site-packages\fastapi\routing.py", line 301, in app
ERROR:        raw_response = await run_endpoint_function(
ERROR:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR:      File "C:\Users\XXX\tabbyAPI\venv\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
ERROR:        return await dependant.call(**values)
ERROR:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR:      File "C:\Users\XXX\tabbyAPI\endpoints\OAI\router.py", line 161, in embeddings
ERROR:        response = await run_with_request_disconnect(
ERROR:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR:      File "C:\Users\XXX\tabbyAPI\common\networking.py", line 87, in run_with_request_disconnect
ERROR:        return call_task.result()
ERROR:               ^^^^^^^^^^^^^^^^^^
ERROR:      File "C:\Users\XXX\tabbyAPI\endpoints\OAI\utils\embeddings.py", line 46, in get_embeddings
ERROR:        EmbeddingObject(
ERROR:      File "C:\Users\XXX\tabbyAPI\venv\Lib\site-packages\pydantic\main.py", line 214, in __init__
ERROR:        validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
ERROR:                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR:    pydantic_core._pydantic_core.ValidationError: 1 validation error for EmbeddingObject
ERROR:    embedding
ERROR:      Input should be a valid list [type=list_type,
input_value='s8BFvWxAYjrc9EC9UEduvOsv...Dychrk7hbwMO669bL159z+9', input_type=str]
ERROR:        For further information visit https://errors.pydantic.dev/2.10/v/list_type

### Additional context

Full request body:
```json
{
	"input": [
		"Test"
	],
	"model": "all-MiniLM-L6-v2",
	"encoding_format": "base64",
	"dimensions": 384
}
```

### Acknowledgements

- [X] I have looked for similar issues before submitting this one.
- [X] I have read the disclaimer, and this issue is related to a code bug. If I have a question, I will use the Discord server.
- [X] I understand that the developers have lives and my issue will be answered when possible.
- [X] I understand the developers of this program are human, and I will ask my questions politely.

**Comment by bdashore3** [comment]
Fixed in 6da65a8fd39a10b80dee3dbebef52dac0e8a5030
