### ISSUE TITLE
Installation / Configuration for AMD GPUs

### ISSUE THREAD

**Issue by cikkle** [theroyallab/tabbyAPI#5]
requirements.txt includes a line for flash-attention but this doesn't currently support AMD GPUs. Even if Flash Attention is disabled in config.yml, running `python main.py` straight after installing requirements gives an error looking for CUDA shared objects:

```
Successfully preprocessed all matching files.
Traceback (most recent call last):
  File "/home/o0/ai/tabbyAPI/main.py", line 7, in <module>
    from model import ModelContainer
  File "/home/o0/ai/tabbyAPI/model.py", line 4, in <module>
    from exllamav2 import(
  File "/home/o0/miniconda3/lib/python3.11/site-packages/exllamav2/__init__.py", line 3, in <module>
    from exllamav2.model import ExLlamaV2
  File "/home/o0/miniconda3/lib/python3.11/site-packages/exllamav2/model.py", line 21, in <module>
    from exllamav2.attn import ExLlamaV2Attention
  File "/home/o0/miniconda3/lib/python3.11/site-packages/exllamav2/attn.py", line 19, in <module>
    import flash_attn
  File "/home/o0/miniconda3/lib/python3.11/site-packages/flash_attn/__init__.py", line 3, in <module>
    from flash_attn.flash_attn_interface import (
  File "/home/o0/miniconda3/lib/python3.11/site-packages/flash_attn/flash_attn_interface.py", line 8, in <module>
    import flash_attn_2_cuda as flash_attn_cuda
ImportError: libcudart.so.12: cannot open shared object file: No such file or directory
```

This is easily fixed just by uninstalling flash attention with

`pip uninstall https://github.com/bdashore3/flash-attention/releases/download/2.3.2-2/flash_attn-2.3.2+cu122-cp311-cp311-win_amd64.whl`

Otherwise everything works fine with ROCm / AMD hardware. It would help AMD users to note the above in the installation instructions in README.md (and list ROCm as an alternative to CUDA in the Prerequisites section to avoid the impression ROCm is unsupported).

**Comment by bdashore3** [comment]
I'll make a note of it in the README. But this shouldn't be an error in exllamav2.

@turboderp maybe adding an ImportError in the except clause will fix this?https://github.com/turboderp/exllamav2/blob/5261d785bcc3ac4cb9d5730e9af5e7af5c70c0f4/exllamav2/attn.py#L214

**Comment by bdashore3** [comment]
I feel like this issue has been solved through `requirements_amd.txt` since it doesn't have FA2 as a dependency. Closing this issue.
