### ISSUE TITLE
Loading model fails with "safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge"

### ISSUE THREAD

**Issue by ristew** [theroyallab/tabbyAPI#53]
Installed within the venv, then tried to load a model (https://huggingface.co/bartowski/dolphin-2.6-mistral-7b-dpo-exl2/tree/4_0) using the API but got the following error:

```
INFO:     127.0.0.1:45536 - "POST /v1/model/load HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/ras/ai/tabbyAPI/venv/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ras/ai/tabbyAPI/venv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ras/ai/tabbyAPI/venv/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/ras/ai/tabbyAPI/venv/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ras/ai/tabbyAPI/venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/home/ras/ai/tabbyAPI/venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/home/ras/ai/tabbyAPI/venv/lib/python3.11/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/home/ras/ai/tabbyAPI/venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/ras/ai/tabbyAPI/venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/ras/ai/tabbyAPI/venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/ras/ai/tabbyAPI/venv/lib/python3.11/site-packages/starlette/routing.py", line 762, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ras/ai/tabbyAPI/venv/lib/python3.11/site-packages/starlette/routing.py", line 782, in app
    await route.handle(scope, receive, send)
  File "/home/ras/ai/tabbyAPI/venv/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/home/ras/ai/tabbyAPI/venv/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/ras/ai/tabbyAPI/venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/ras/ai/tabbyAPI/venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/ras/ai/tabbyAPI/venv/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/ras/ai/tabbyAPI/venv/lib/python3.11/site-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/home/ras/ai/tabbyAPI/venv/lib/python3.11/site-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ras/ai/tabbyAPI/venv/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ras/ai/tabbyAPI/main.py", line 185, in load_model
    MODEL_CONTAINER = ModelContainer(model_path.resolve(), False, **load_data)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ras/ai/tabbyAPI/model.py", line 115, in __init__
    self.config.prepare()
  File "/home/ras/ai/tabbyAPI/venv/lib/python3.11/site-packages/exllamav2/config.py", line 188, in prepare
    with safe_open(st_file, framework = "pt", device = "cpu") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge
```

with the command:
```
curl -H 'Content-type: application/json' -H 'X-Admin-Key: ---' localhost:5000/v1/model/load --data '{"name":"dolphin-2.6-mistral-7b-dpo-exl2"}'
```

I got the same error with the other model I tried (https://huggingface.co/LoneStriker/internlm2-20b-llama-3.0bpw-h6-exl2).

**Comment by bdashore3** [comment]
I tried loading both models using stock dependencies. They loaded and processed successfully on my end, therefore this is a user error.

Please take a look at the folder you downloaded the model in and make sure that the files are correct and aren't corrupted. To download a model from huggingface (let's use [bartowski/dolphin-2.6-mistral-7b-dpo-exl2l](https://huggingface.co/bartowski/dolphin-2.6-mistral-7b-dpo-exl2/tree/4_0) as an example)

Prerequisites: Make sure `huggingface_hub` is installed and updated to the latest version:
```
mkdir dolphin-2.6-mistral-7b-dpo-exl2
huggingface-cli download bartowski/dolphin-2.6-mistral-7b-dpo-exl2 --local-dir dolphin-2.6-mistral-7b-dpo-exl2 --local-dir-use-symlinks False --revision 4_0
```

`--revision` indicates the branch that you're using. Remove it for lonestriker's repos.

And in `config.yml`, set `model_name` to `dolphin-2.6-mistral-7b-dpo-exl2` which is the directory where the model was downloaded in.

Please join the [Discord Server](https://discord.gg/sYQxnuD7Fj) if you need any more help. Closing this issue.
