### ISSUE TITLE
[BUG] Cannot start after update (IndexError: piece id is out of range.).

### ISSUE THREAD

**Issue by ThomasBaruzier** [theroyallab/tabbyAPI#62]
I just updated the code using git pull, and the following error occurs.
I tried to redo everything from scratch with the same results.
I might suspect that the program is trying to start the ROCm version of the API, since I have a dual GPU setup with a RX 5700 and a RTX 3090, but fails at doing so.
A possible fix would let the user chose its main GPU in the config file.
Please tell me if I am wrong, I do not know python very well.

```
(venv) ~/files/ai/tabbyAPI ./start.sh 
Activating venv
pip 24.0 from /home/tyra/files/ai/tabbyAPI/venv/lib/python3.11/site-packages/pip (python 3.11)
Requirement already satisfied: fastapi in ./venv/lib/python3.11/site-packages (from -r requirements-nowheel.txt (line 2)) (0.109.2)
Requirement already satisfied: pydantic>=2.0.0 in ./venv/lib/python3.11/site-packages (from -r requirements-nowheel.txt (line 3)) (2.6.1)
Requirement already satisfied: PyYAML in ./venv/lib/python3.11/site-packages (from -r requirements-nowheel.txt (line 4)) (6.0.1)
Requirement already satisfied: progress in ./venv/lib/python3.11/site-packages (from -r requirements-nowheel.txt (line 5)) (1.6)
Requirement already satisfied: uvicorn in ./venv/lib/python3.11/site-packages (from -r requirements-nowheel.txt (line 6)) (0.27.0.post1)
Requirement already satisfied: jinja2>=3.0.0 in ./venv/lib/python3.11/site-packages (from -r requirements-nowheel.txt (line 7)) (3.1.3)
Requirement already satisfied: colorlog in ./venv/lib/python3.11/site-packages (from -r requirements-nowheel.txt (line 8)) (6.8.2)
Requirement already satisfied: starlette<0.37.0,>=0.36.3 in ./venv/lib/python3.11/site-packages (from fastapi->-r requirements-nowheel.txt (line 2)) (0.36.3)
Requirement already satisfied: typing-extensions>=4.8.0 in ./venv/lib/python3.11/site-packages (from fastapi->-r requirements-nowheel.txt (line 2)) (4.9.0)
Requirement already satisfied: annotated-types>=0.4.0 in ./venv/lib/python3.11/site-packages (from pydantic>=2.0.0->-r requirements-nowheel.txt (line 3)) (0.6.0)
Requirement already satisfied: pydantic-core==2.16.2 in ./venv/lib/python3.11/site-packages (from pydantic>=2.0.0->-r requirements-nowheel.txt (line 3)) (2.16.2)
Requirement already satisfied: click>=7.0 in ./venv/lib/python3.11/site-packages (from uvicorn->-r requirements-nowheel.txt (line 6)) (8.1.7)
Requirement already satisfied: h11>=0.8 in ./venv/lib/python3.11/site-packages (from uvicorn->-r requirements-nowheel.txt (line 6)) (0.14.0)
Requirement already satisfied: MarkupSafe>=2.0 in ./venv/lib/python3.11/site-packages (from jinja2>=3.0.0->-r requirements-nowheel.txt (line 7)) (2.1.5)
Requirement already satisfied: anyio<5,>=3.4.0 in ./venv/lib/python3.11/site-packages (from starlette<0.37.0,>=0.36.3->fastapi->-r requirements-nowheel.txt (line 2)) (4.2.0)
Requirement already satisfied: idna>=2.8 in ./venv/lib/python3.11/site-packages (from anyio<5,>=3.4.0->starlette<0.37.0,>=0.36.3->fastapi->-r requirements-nowheel.txt (line 2)) (3.6)
Requirement already satisfied: sniffio>=1.1 in ./venv/lib/python3.11/site-packages (from anyio<5,>=3.4.0->starlette<0.37.0,>=0.36.3->fastapi->-r requirements-nowheel.txt (line 2)) (1.3.0)
No ROCm runtime is found, using ROCM_HOME='/opt/rocm'
INFO: ExllamaV2 version: 0.0.13.post1
INFO: Your API key is: fbfb8d7734742cb00274333e7c33778f
INFO: Your admin key is: 8b5c5f15bdc78ed5239c8a2ecb5ebd88
INFO: 
INFO: If these keys get compromised, make sure to delete api_tokens.yml and restart the server. Have fun!
INFO: Generation logging is enabled for: prompts, generation params
INFO: Disabling GPU split because one GPU is in use.
INFO: Attempting to load a prompt template if present.
INFO: Using template from_tokenizer_config for chat completions.
Traceback (most recent call last):
  File "/home/tyra/files/ai/tabbyAPI/start.py", line 69, in <module>
    entrypoint(convert_args_to_dict(args, parser))
  File "/home/tyra/files/ai/tabbyAPI/main.py", line 636, in entrypoint
    for module, modules in load_status:
  File "/home/tyra/files/ai/tabbyAPI/backends/exllamav2/model.py", line 344, in load_gen
    self.tokenizer = ExLlamaV2Tokenizer(self.config)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tyra/files/ai/tabbyAPI/venv/lib/python3.11/site-packages/exllamav2/tokenizer.py", line 119, in __init__
    self.eos_token = (self.tokenizer.eos_token() or self.extended_id_to_piece.get(self.eos_token_id, None)) or self.tokenizer.id_to_piece(self.eos_token_id)
                                                                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tyra/files/ai/tabbyAPI/venv/lib/python3.11/site-packages/exllamav2/tokenizers/spm.py", line 28, in id_to_piece
    return self.spm.id_to_piece(idx)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tyra/files/ai/tabbyAPI/venv/lib/python3.11/site-packages/sentencepiece/__init__.py", line 1045, in _batched_func
    return _func(self, arg)
           ^^^^^^^^^^^^^^^^
  File "/home/tyra/files/ai/tabbyAPI/venv/lib/python3.11/site-packages/sentencepiece/__init__.py", line 1038, in _func
    raise IndexError('piece id is out of range.')
IndexError: piece id is out of range.
```

The same error occurs when using my personnal start.sh script:
```
#!/bin/bash

screen -ls | grep -q 'lchat-api' && exit
cd "$(dirname "$0")" || exit
[ -d "/home/tyra/files/ai/envs/exllama" ] || exit
source /home/tyra/files/ai/envs/exllama/bin/activate
#echo "Logfile: $PWD/lchat-api.log"
screen -dmS 'lchat-api' -L -Logfile lchat-api.log bash -c '
  sudo nvidia-smi -pl 370
  sudo nvidia-smi --lock-memory-clocks=0,9751
  sudo nvidia-smi --lock-gpu-clocks=0,1500 --mode=1
  __NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia python3 main.py
  read -p 'Done. Press any key to continue.'
'
```

**Comment by bdashore3** [comment]
Please send the model URL? It looks like you're trying to load a model and the tokenizer can't read its tokenizer.model.

**Comment by ThomasBaruzier** [comment]
Indeed, it seems to be a model problem.
This was done using solar 10.7b, but using a different finetune fixed my issue. I will investigate further on the not working model, but I suspect it is just a download issue.
Thank you.

**Comment by bdashore3** [comment]
Solved. Closing issue.
